#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('CorePHP Slim Framework installer', '0.0.1.1');
$app->add(new CorePHP\Slim\Console\AppInitCommand);
$app->add(new CorePHP\Slim\Console\NewModelCommand);
$app->add(new CorePHP\Slim\Console\NewControllerCommand);
$app->add(new CorePHP\Slim\Console\AddDependencyCommand);

$app->run();